### ISSUE TITLE
[Question] How does Signum code work? Can provide a simple breakdown/explainer of the code structure?

### ISSUE THREAD

**Issue by simkimsia** [MintStudios/Signum#20]
I saw there's a Scene folder but I cannot find any actual Nodes.

Do you use GDScript to write this project?

Thank you

## Update

Sorry I started with some dumb questions.

> Do you use GDScript to write this project?

I realized that obviously you did, since Github says 100% GDScript

> I saw there's a Scene folder but I cannot find any actual Nodes.

I search using the command `get_node` and found these. Am I correct that this is the full list of Godot nodes you use to build the text editor?

![image](https://user-images.githubusercontent.com/245021/92200286-0c843d00-eeac-11ea-9ba4-c3d7a38b59b6.png)

Any other nodes I might have overlooked?

**Comment by MintStudios** [comment]
If you want to look at any of the nodes, you need to open the project in godot and look at the hierarchy. As for looking at the nodes in code, which is not recommended, you can look at `.tscn` files, where you can see data for a node in a script. Double click on the signum project in godot, which will take you here:
![image](https://user-images.githubusercontent.com/54677274/92247752-a2f93400-ee95-11ea-898c-8f23e4566466.png)

Depending on where your nodes are, you will see them. My nodes are on the top left.

If you want to understand how the codebase works, you need to play around with the code. I think I have commented my code nicely, so that can help. One question - how familiar are you with GDScript?

**Comment by simkimsia** [comment]
> One question - how familiar are you with GDScript

Not particularly. I just started messing with godot recently.

I got this as well

![image](https://user-images.githubusercontent.com/245021/92321458-ae4a8c00-f05c-11ea-8e7e-be918bf76e39.png)

Can nodes be nested? It seems that way

![image](https://user-images.githubusercontent.com/245021/92321512-3335a580-f05d-11ea-88bb-d24740cf9bd6.png)

**Comment by superRaptor911** [comment]
Yes nodes can be nested and you can add / remove nodes at runtime.

**Comment by simkimsia** [comment]
Thanks
