### ISSUE TITLE
Reduce FPS !

### ISSUE THREAD

**Issue by superRaptor911** [MintStudios/Signum#9]
Currently the text editor runs at 60 fps which is not required and by reducing fps , cpu usage can be reduced and will cause less heating.

**Comment by MintStudios** [comment]
Hmm, yes. What fps would you recommend?

**Comment by slooths** [comment]
It might also be worth looking into [low_processor_usage_mode](https://docs.godotengine.org/en/stable/classes/class_os.html?#class-os-property-low-processor-usage-mode). From the `ProjectSettings` documentation:

"If `true`, enables low-processor usage mode. This setting only works on desktop platforms. The screen is not redrawn if nothing changes visually. This is meant for writing applications and editors, but is pretty useless (and can hurt performance) in most games."

I'm not sure how much of an impact this would have with the current codebase since it is rather small, but it may be something to keep in mind for future performance benefits.
